replicas: 2
image:
  repository: "ghcr.io/digitalproductschool/test-backend/frontend"
  tag: "1.0.3"
  pullPolicy: Always
imagePullSecrets:
  - name: ghcr-credentials
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 100
  runAsGroup: 102
  fsGroup: 102
  fsGroupChangePolicy: "OnRootMismatch"
  seccompProfile:
    type: "RuntimeDefault"
securityContext:
  capabilities:
    drop: ["ALL"]
  allowPrivilegeEscalation: false
ingress:
  host: "dev.test-backend.dpschool.app"
  className: nginx
tls:
  enabled: true