name: Deploy Frontend to Prod
run-name: Prod-frontend
on:
    # run it on push to the staging repository branch
    push:
      branches: 
        - master
      paths: 
        - 'frontend/**'

env: 
    CONTEXT: frontend
    ENV: prod
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Variables
        id: vars
        run: |
          echo "VERSION=1.0.${{ github.run_number }}" >> "$GITHUB_ENV"
          echo "IMAGE=ghcr.io/digitalproductschool/${{ github.event.repository.name }}/${{ env.CONTEXT }}" >> "$GITHUB_ENV"
          echo "TAG=ghcr.io/digitalproductschool/${{ github.event.repository.name }}/${{ env.CONTEXT }}:1.0.${{ github.run_number }}" >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.TAG }}
          context: ./${{ env.CONTEXT }}

      - name: Update Helm
        run: |
          chmod +x deployment/scripts/update-image-value.sh 
          ./deployment/scripts/update-image-value.sh ${{ env.VERSION }} ${{ env.IMAGE }} ${{ env.ENV }} ${{ env.CONTEXT }} ${{ github.event.repository.name }}

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy ${{ env.CONTEXT }} to ${{ env.ENV }} 🤖"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_ACTIONS_BOT_ACCESS_TOKEN}}
          branch: ${{ github.ref }}